name = "A KRAVITZ"
description = "Hip-hop artist crafting introspective lyrics with thoughtful wordplay and vivid imagery."
keywords = "A KRAVITZ, rapper, hip-hop, music, introspective lyrics, thoughtful wordplay"
image = "akravitz.jpeg"  # You'll need to replace this with your actual image file
theme = "dark"
primary_color = "#ff4500"  # Mars-like orange-red color
text_align = "center"
# gtag_id = "G-33WB8LVHR6"  # You may want to replace this with your own Google Analytics ID if you have one
base_url = "akravitzmusic.com"  # Replace with your actual website URL

[[sections]]
title = "Music"
description = "Check out some of my tracks"
direction = "column"
item_style = "outline"
[[sections.items]]
title = "Made It"
description = "A journey through personal growth and self-reflection"
url = "https://open.spotify.com/track/6u2RcZ2kxhcV8DhqoTsCez"
[[sections.items]]
title = "Icarus"  # Replace with actual song titles
description = "Exploring the balance between ambition and caution"
url = "https://open.spotify.com/artist/42l1bkQwYGfGjIEj2LMGEn"  # Replace with actual song URL when available
[[sections.items]]
title = "Leaning On"  # Replace with actual song titles
description = "Navigating relationships and personal struggles"
url = "https://open.spotify.com/artist/42l1bkQwYGfGjIEj2LMGEn"  # Replace with actual song URL when available

[[sections]]
title = "Links"
description = "Connect with me on these platforms"
direction = "row"
item_style = "filled"
[[sections.items]]
title = "TikTok"
url = "https://www.tiktok.com/@akravitzmusic"
[[sections.items]]
title = "Instagram"
url = "https://www.instagram.com/akravitzmusic"
[[sections.items]]
title = "Spotify"
url = "https://open.spotify.com/artist/42l1bkQwYGfGjIEj2LMGEn"
[[sections.items]]
title = "Apple Music"
url = "https://music.apple.com/us/artist/a-kravitz/404363729"
